### PR TITLE
Replace diactoros zend with laminas

### LINKED ISSUE #2: zendframework/zend-diactoros is abandoned
Hi, 
composer tells me that `zendframework/zend-diactoros` is abandoned and should be replaced.

`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.`

Any plans to replace that package? And is this package still actively maintained?

Thanks in advance.

### PR DESCRIPTION
**Pull request by andrewtweber**
Seems like a simple composer package + namespace change is all it needed.

However, your test server seems to be down so I wasn't able to run the tests, so please don't merge unless you're able to confirm

Resolves #2

### CODE REVIEW

**Comment by dvn-github** [comment]
Hi buddies, can we do the merge of this fix into master? @andrewtweber @meng-tian

**Comment by allan-simon** [comment]
@meng-tian is there any thing we can do to help  merging this PR ? :)

**Comment by realmtian** [comment]
Hi all,

Sorry for the late response. I did looked into this pull request and came up with some ideas https://github.com/meng-tian/soap-http-binding/issues/4 but haven't managed to find a time to implement it. I have the plan of removing concrete stream and request types from this library in the future.

This change looks good in the mean time.

Thank you for contributing this library.

**Comment by realmtian** [comment]
By the way, I've also pushed a change to use local WSDL, so the tests should now passing.

**Comment by realmtian** [comment]
A new release is also published https://github.com/meng-tian/soap-http-binding/releases/tag/0.2.4

**Pull request merged**
